name: Feature request
description: Suggest an improvement or new component
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: I'm frustrated when ...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe your preferred solution
      placeholder: I’d like a component that ...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative approaches?

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - hero
        - motion
        - input
        - docs
        - tooling
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Links, references, screenshots
